"""
training/train_classical_unet.py
==================================
Trains Attention U-Net on classical pseudo-masks generated by
    refinement/classical_mask_generator.py --dataset

Run (CPU — ~50 min for 50 epochs on 5712 images):
    python training/train_classical_unet.py

Run with custom settings:
    python training/train_classical_unet.py --epochs 30 --batch_size 4

For GPU (Colab/Kaggle) add:
    python training/train_classical_unet.py --batch_size 16 --epochs 50

Prerequisite:
    python refinement/classical_mask_generator.py --dataset
    (generates outputs/classical_masks/ — run once)

Output:
    checkpoints/unet/best_unet.pth          <- used by pipeline.py
    checkpoints/unet/curves.png             <- training curves
    checkpoints/unet/vis/ep*.png            <- sample predictions per epoch
    unet_train.log                          <- full training log
"""
from __future__ import annotations

import argparse
import logging
import sys
import time
from pathlib import Path

import cv2
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split

import albumentations as A
from albumentations.pytorch import ToTensorV2

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from segmentation.attention_unet import AttentionUNet
from segmentation.losses         import CombinedSegLoss
from segmentation.metrics        import compute_all_metrics

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s — %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("unet_train.log", encoding="utf-8"),
    ],
)
log = logging.getLogger("ClassicalUNetTrainer")


# ── Dataset ───────────────────────────────────────────────────────────────────

CLASSES = ["glioma", "meningioma", "notumor", "pituitary"]
MEAN    = [0.485, 0.456, 0.406]
STD     = [0.229, 0.224, 0.225]


class ClassicalSegDataset(Dataset):
    """
    Pairs:
        {data_root}/{cls}/{stem}.jpg
    with:
        {mask_root}/{cls}/{stem}_mask.png

    Generated by:
        python refinement/classical_mask_generator.py --dataset
    """

    def __init__(
        self,
        data_root:  str,
        mask_root:  str,
        image_size: int  = 224,
        train:      bool = True,
    ):
        self.pairs: list[tuple[Path, Path]] = []

        data_root = Path(data_root)
        mask_root = Path(mask_root)

        for cls in CLASSES:
            img_dir  = data_root / cls
            mask_dir = mask_root / cls
            if not img_dir.exists():
                continue
            for ext in ("*.jpg", "*.jpeg", "*.png"):
                for img_path in sorted(img_dir.glob(ext)):
                    mask_path = mask_dir / (img_path.stem + "_mask.png")
                    if mask_path.exists():
                        self.pairs.append((img_path, mask_path))

        if not self.pairs:
            raise FileNotFoundError(
                f"No image-mask pairs found.\n"
                f"  images: {data_root}\n"
                f"  masks : {mask_root}\n"
                f"Run:  python refinement/classical_mask_generator.py --dataset"
            )

        log.info(f"Dataset: {len(self.pairs)} pairs  "
                 f"({'train' if train else 'val'} transforms)")

        if train:
            self.tfm = A.Compose([
                A.Resize(image_size, image_size),
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.3),
                A.RandomRotate90(p=0.5),
                A.ShiftScaleRotate(
                    shift_limit=0.10, scale_limit=0.15,
                    rotate_limit=30, p=0.5),
                A.RandomBrightnessContrast(p=0.4),
                A.GaussNoise(p=0.3),
                A.Normalize(mean=MEAN, std=STD),
                ToTensorV2(),
            ])
        else:
            self.tfm = A.Compose([
                A.Resize(image_size, image_size),
                A.Normalize(mean=MEAN, std=STD),
                ToTensorV2(),
            ])

    def __len__(self) -> int:
        return len(self.pairs)

    def __getitem__(self, idx: int) -> dict:
        img_path, mask_path = self.pairs[idx]

        bgr  = cv2.imread(str(img_path))
        if bgr is None:
            bgr = np.zeros((224, 224, 3), dtype=np.uint8)
        img  = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)

        m = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        mask = (m / 255.0).astype(np.float32) if m is not None \
               else np.zeros(img.shape[:2], dtype=np.float32)

        result  = self.tfm(image=img, mask=mask)
        img_t   = result["image"].float()
        mask_t  = result["mask"].float().unsqueeze(0)   # (1, H, W)

        return {"image": img_t, "mask": mask_t}


# ── Visualisation ─────────────────────────────────────────────────────────────

_DARK = "#0f172a"
_CYAN = "#00d4ff"


def _denorm(t: torch.Tensor) -> np.ndarray:
    arr = t.cpu().float().numpy().transpose(1, 2, 0)
    arr = arr * np.array(STD) + np.array(MEAN)
    return arr.clip(0, 1)


def save_vis(
    model:     AttentionUNet,
    loader:    DataLoader,
    epoch:     int,
    out_dir:   Path,
    device:    torch.device,
    n:         int = 4,
) -> None:
    model.eval()
    samples: list[tuple] = []
    with torch.no_grad():
        for batch in loader:
            imgs  = batch["image"].to(device)
            masks = batch["mask"].to(device)
            probs = torch.sigmoid(model(imgs))
            for i in range(min(n - len(samples), imgs.size(0))):
                samples.append((
                    _denorm(imgs[i]),
                    masks[i, 0].cpu().numpy(),
                    probs[i, 0].cpu().numpy(),
                ))
            if len(samples) >= n:
                break

    if not samples:
        return

    fig, axes = plt.subplots(len(samples), 3,
                             figsize=(9, 3 * len(samples)), facecolor=_DARK)
    if len(samples) == 1:
        axes = [axes]

    for row, (img, gt, pred) in enumerate(samples):
        for col, (arr, title, cmap) in enumerate([
            (img,  "MRI Input",       None),
            (gt,   "Classical Mask",  "gray"),
            (pred, "U-Net Prediction","RdYlGn"),
        ]):
            ax = axes[row][col]
            ax.imshow(arr, cmap=cmap, vmin=0, vmax=1)
            if row == 0:
                ax.set_title(title, color=_CYAN, fontsize=9, fontweight="bold")
            ax.axis("off")

    plt.suptitle(f"Epoch {epoch:03d}", color="white", fontsize=11)
    plt.tight_layout(pad=0.4)
    vis_dir = out_dir / "vis"
    vis_dir.mkdir(exist_ok=True)
    fig.savefig(vis_dir / f"ep{epoch:03d}.png", dpi=90,
                bbox_inches="tight", facecolor=_DARK)
    plt.close(fig)


def plot_curves(history: dict, out_dir: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(15, 4), facecolor=_DARK)
    for ax, (key, color) in zip(axes, [
        ("loss", "#ef4444"),
        ("dice", "#10b981"),
        ("iou",  "#3b82f6"),
    ]):
        ax.plot(history[f"tr_{key}"],  color=color, lw=2, label="Train")
        ax.plot(history[f"val_{key}"], color=color, lw=2, ls="--",
                alpha=0.7, label="Val")
        ax.set_title(key.upper(), color="white", fontsize=11)
        ax.set_facecolor(_DARK)
        ax.tick_params(colors="#94a3b8")
        ax.legend(facecolor="#1e293b", labelcolor="white", fontsize=8)
        for sp in ax.spines.values():
            sp.set_edgecolor("#334155")
    plt.suptitle("Attention U-Net — Classical Mask Training",
                 color="white", fontsize=13)
    plt.tight_layout()
    fig.savefig(out_dir / "curves.png", dpi=100,
                bbox_inches="tight", facecolor=_DARK)
    plt.close(fig)


# ── One epoch ─────────────────────────────────────────────────────────────────

def run_epoch(
    model:     AttentionUNet,
    loader:    DataLoader,
    criterion: CombinedSegLoss,
    optimizer: torch.optim.Optimizer | None,
    device:    torch.device,
    train:     bool,
) -> dict[str, float]:
    model.train() if train else model.eval()

    totals = {"loss": 0.0, "dice": 0.0, "iou": 0.0}
    n = 0

    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for batch in loader:
            imgs  = batch["image"].to(device)
            masks = batch["mask"].to(device)

            logits = model(imgs)
            loss   = criterion(logits, masks)   # scalar (CombinedSegLoss)

            if train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

            bs   = imgs.size(0)
            met  = compute_all_metrics(logits.detach(), masks)
            totals["loss"] += loss.item() * bs
            totals["dice"] += met["dice"]  * bs
            totals["iou"]  += met["iou"]   * bs
            n += bs

    return {k: v / max(n, 1) for k, v in totals.items()}


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Train Attention U-Net with classical pseudo-masks",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--data_root",    default="Project/Training",
                   help="Root folder containing class subfolders")
    p.add_argument("--mask_root",    default="outputs/classical_masks",
                   help="Root folder with classical masks (from --dataset)")
    p.add_argument("--image_size",   type=int,   default=224)
    p.add_argument("--val_split",    type=float, default=0.15)
    p.add_argument("--epochs",       type=int,   default=50)
    p.add_argument("--batch_size",   type=int,   default=8)
    p.add_argument("--lr",           type=float, default=1e-4)
    p.add_argument("--base_filters", type=int,   default=16,
                   help="16 → ~470K params (fast CPU), 32 → ~1.8M params")
    p.add_argument("--num_workers",  type=int,   default=0)
    p.add_argument("--seed",         type=int,   default=42)
    p.add_argument("--vis_every",    type=int,   default=5,
                   help="Save sample visualisations every N epochs (0=never)")
    p.add_argument("--out_dir",      default="checkpoints/unet")
    return p.parse_args()


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    args    = parse_args()
    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    log.info("=" * 64)
    log.info("  Attention U-Net — Classical Pseudo-Mask Training")
    log.info(f"  Device      : {device}")
    log.info(f"  Data        : {args.data_root}")
    log.info(f"  Masks       : {args.mask_root}")
    log.info(f"  Image size  : {args.image_size}")
    log.info(f"  Base filters: {args.base_filters}")
    log.info(f"  Epochs      : {args.epochs}  |  Batch: {args.batch_size}"
             f"  |  LR: {args.lr}")
    log.info("=" * 64)

    # ── Dataset ───────────────────────────────────────────────────────────
    full_ds  = ClassicalSegDataset(
        args.data_root, args.mask_root, args.image_size, train=True)
    val_ds   = ClassicalSegDataset(
        args.data_root, args.mask_root, args.image_size, train=False)

    n_total = len(full_ds)
    n_val   = max(1, int(n_total * args.val_split))
    n_train = n_total - n_val

    gen          = torch.Generator().manual_seed(args.seed)
    tr_sub, _    = random_split(full_ds, [n_train, n_val], generator=gen)
    _, va_sub    = random_split(val_ds,  [n_train, n_val], generator=gen)

    loader_kw = dict(
        batch_size  = args.batch_size,
        num_workers = args.num_workers,
        pin_memory  = torch.cuda.is_available(),
    )
    train_loader = DataLoader(tr_sub, shuffle=True,  **loader_kw)
    val_loader   = DataLoader(va_sub, shuffle=False, **loader_kw)

    log.info(f"Train: {n_train}   Val: {n_val}   Total: {n_total}")

    # ── Model ─────────────────────────────────────────────────────────────
    model = AttentionUNet(
        in_channels  = 3,
        base_filters = args.base_filters,
        bilinear     = True,
    ).to(device)

    n_params = model.count_parameters()
    log.info(f"AttentionUNet parameters: {n_params:,}")

    # ── Optimiser + loss + scheduler ──────────────────────────────────────
    criterion = CombinedSegLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr,
                                  weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", factor=0.5, patience=6, min_lr=1e-7)

    # ── Training loop ─────────────────────────────────────────────────────
    history: dict[str, list[float]] = {
        k: [] for k in ["tr_loss", "tr_dice", "tr_iou",
                         "val_loss", "val_dice", "val_iou"]
    }
    best_dice = 0.0
    best_ckpt: Path | None = None

    for epoch in range(1, args.epochs + 1):
        t0  = time.time()
        tr  = run_epoch(model, train_loader, criterion, optimizer,
                        device, train=True)
        val = run_epoch(model, val_loader,   criterion, None,
                        device, train=False)

        scheduler.step(val["dice"])

        for k in ["loss", "dice", "iou"]:
            history[f"tr_{k}"].append(tr[k])
            history[f"val_{k}"].append(val[k])

        lr_now  = optimizer.param_groups[0]["lr"]
        elapsed = time.time() - t0
        log.info(
            f"Ep {epoch:03d}/{args.epochs}  "
            f"TR  loss={tr['loss']:.4f}  dice={tr['dice']:.4f}"
            f"  iou={tr['iou']:.4f}  |  "
            f"VAL loss={val['loss']:.4f}  dice={val['dice']:.4f}"
            f"  iou={val['iou']:.4f}  "
            f"lr={lr_now:.2e}  [{elapsed:.1f}s]"
        )

        # ── Save best checkpoint (compatible with pipeline.py) ─────────────
        if val["dice"] > best_dice:
            best_dice = val["dice"]
            ckpt_path = out_dir / "best_unet.pth"
            torch.save({
                "epoch":              epoch,
                "model_state_dict":   model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "val_dice":           best_dice,
                "val_iou":            val["iou"],
                "config": {
                    "architecture": "attention_unet",
                    "in_channels":  3,
                    "base_filters": args.base_filters,
                    "bilinear":     True,
                    "image_size":   args.image_size,
                    "threshold":    0.45,
                },
            }, ckpt_path)
            best_ckpt = ckpt_path
            log.info(f"  *** New best -> {ckpt_path.name}  (dice={best_dice:.4f})")

        # ── Per-epoch visualisation ────────────────────────────────────────
        if args.vis_every > 0 and (epoch % args.vis_every == 0 or epoch == 1):
            save_vis(model, val_loader, epoch, out_dir, device)

    # ── Post-training ──────────────────────────────────────────────────────
    plot_curves(history, out_dir)

    log.info("=" * 64)
    log.info("  Training complete")
    log.info(f"  Best Val Dice : {best_dice:.4f}")
    log.info(f"  Best checkpoint: {best_ckpt}")
    log.info(f"  Curves         : {out_dir / 'curves.png'}")
    log.info("=" * 64)


if __name__ == "__main__":
    main()
